name: 'Entrega Semana 2 - Modelos con Pydantic'
description: 'Envía la URL de tu repositorio público con la semana 2'
title: '[SEM2] Entrega - <Ficha> - <ApellidoNombre>'
labels: ['semana2', 'submission']
body:
  - type: input
    id: student_name
    attributes:
      label: Nombre completo
      placeholder: 'Tu nombre y apellido'
    validations:
      required: true
  - type: input
    id: ficha
    attributes:
      label: Ficha / Curso
      placeholder: 'Ej: 3147246'
    validations:
      required: true
  - type: input
    id: repo_url
    attributes:
      label: URL del repositorio (público)
      placeholder: 'https://github.com/usuario/ficha-apellido-nombre-fastapi-semana2'
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notas (opcional)
      placeholder: 'Comentarios para el instructor'
