week_info:
  number: 5
  title: 'Testing y Documentación Avanzada'
  description: 'Testing automatizado, documentación API y deployment preparation'
  passing_threshold: 75
  repository_template: 'ficha-apellido-nombre-fastapi-semana5'

learning_objectives:
  - 'Implementar testing automatizado con pytest'
  - 'Crear tests de integración para APIs'
  - 'Documentar APIs con OpenAPI personalizado'
  - 'Configurar testing de base de datos'
  - 'Preparar aplicación para deployment'

categories:
  testing_setup:
    weight: 35
    description: 'Configuración y estructura de testing'
    checks:
      - name: 'pytest_configuration'
        points: 8
        description: 'Configuración correcta de pytest'
        required: true
      - name: 'test_dependencies'
        points: 7
        description: 'Dependencies de testing (pytest, httpx, etc.)'
        required: true
      - name: 'test_structure'
        points: 8
        description: 'Estructura organizada de tests'
        required: true
      - name: 'test_database_config'
        points: 12
        description: 'Base de datos de testing separada'
        required: true

  unit_testing:
    weight: 25
    description: 'Tests unitarios y de componentes'
    checks:
      - name: 'model_tests'
        points: 8
        description: 'Tests de modelos Pydantic y SQLAlchemy'
        required: true
      - name: 'utility_function_tests'
        points: 7
        description: 'Tests de funciones utilitarias'
        required: true
      - name: 'business_logic_tests'
        points: 10
        description: 'Tests de lógica de negocio'
        required: true

  integration_testing:
    weight: 25
    description: 'Tests de integración de API'
    checks:
      - name: 'endpoint_tests'
        points: 10
        description: 'Tests de todos los endpoints principales'
        required: true
      - name: 'database_integration_tests'
        points: 8
        description: 'Tests de operaciones de base de datos'
        required: true
      - name: 'error_handling_tests'
        points: 7
        description: 'Tests de manejo de errores'
        required: true

  documentation:
    weight: 15
    description: 'Documentación avanzada de API'
    checks:
      - name: 'openapi_customization'
        points: 5
        description: 'Personalización de documentación OpenAPI'
        required: false
      - name: 'api_examples'
        points: 5
        description: 'Ejemplos de requests/responses en docs'
        required: false
      - name: 'deployment_readme'
        points: 5
        description: 'Documentación para deployment'
        required: true

automation:
  timeout_seconds: 300
  required_files:
    - 'main.py'
    - 'requirements.txt'
    - 'tests/'

  dependency_checks:
    - package: 'pytest'
      required: true
    - package: 'httpx'
      required: true
    - package: 'pytest-asyncio'
      required: false

  test_patterns:
    - pattern: 'test_*.py'
      directory: 'tests/'
    - pattern: '*_test.py'
      directory: 'tests/'
