week_info:
  number: 4
  title: 'Bases de Datos Avanzadas con FastAPI'
  description: 'SQLAlchemy avanzado: migraciones, relaciones, consultas complejas'
  passing_threshold: 75
  repository_template: 'ficha-apellido-nombre-fastapi-semana4'

learning_objectives:
  - 'Implementar migraciones con Alembic'
  - 'Crear relaciones complejas entre modelos'
  - 'Desarrollar consultas SQLAlchemy avanzadas'
  - 'Organizar código en estructura profesional'
  - 'Optimizar rendimiento de base de datos'

categories:
  advanced_database:
    weight: 35
    description: 'Configuración avanzada de base de datos'
    checks:
      - name: 'alembic_migrations'
        points: 12
        description: 'Migraciones con Alembic configuradas'
        required: true
      - name: 'complex_relationships'
        points: 10
        description: 'Relaciones many-to-many, one-to-many'
        required: true
      - name: 'database_constraints'
        points: 8
        description: 'Constraints, índices y validaciones'
        required: true
      - name: 'connection_pooling'
        points: 5
        description: 'Configuración de pool de conexiones'
        required: false

  advanced_crud:
    weight: 30
    description: 'Operaciones CRUD avanzadas'
    checks:
      - name: 'complex_queries'
        points: 10
        description: 'Queries con joins y filtros complejos'
        required: true
      - name: 'bulk_operations'
        points: 8
        description: 'Operaciones en lote (bulk insert/update)'
        required: true
      - name: 'transaction_management'
        points: 7
        description: 'Manejo de transacciones'
        required: true
      - name: 'pagination_advanced'
        points: 5
        description: 'Paginación y ordenamiento avanzado'
        required: true

  code_organization:
    weight: 20
    description: 'Estructura profesional del código'
    checks:
      - name: 'models_separation'
        points: 8
        description: 'Modelos en archivos separados (models/)'
        required: true
      - name: 'schemas_separation'
        points: 6
        description: 'Schemas en archivos separados (schemas/)'
        required: true
      - name: 'repository_pattern'
        points: 6
        description: 'Patrón Repository o servicios'
        required: false

  performance_optimization:
    weight: 15
    description: 'Optimización y rendimiento'
    checks:
      - name: 'query_optimization'
        points: 6
        description: 'Queries optimizadas (eager loading, etc.)'
        required: true
      - name: 'database_indexing'
        points: 5
        description: 'Índices en campos relevantes'
        required: true
      - name: 'caching_strategy'
        points: 4
        description: 'Estrategia básica de caching'
        required: false

automation:
  timeout_seconds: 300
  required_files:
    - 'main.py'
    - 'requirements.txt'
    - 'models/'
    - 'schemas/'
    - 'alembic.ini'
    - 'alembic/'

  dependency_checks:
    - package: 'sqlalchemy'
      min_version: '1.4.0'
    - package: 'alembic'
      required: true
    - package: 'fastapi'
      min_version: '0.100.0'

  advanced_checks:
    - feature: 'migrations'
      files: ['alembic/versions/*.py']
      required: true
    - feature: 'relationships'
      patterns: ['relationship(', 'foreign_key', 'ForeignKey']
      required: true
    - feature: 'organization'
      structure: ['models/', 'schemas/', 'services/']
      required: true
